import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
    {
      id:'1',
      name: 'Pizza Pepperoni',
      donor: 'John',
      location: 'Street1',
      contact: 9856213548,
      type:'Non-Veg',
      expiry:"24-03-2024",
      stars: 4.5,
      imageUrl: 'assets/food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id:'2',
      name: 'Meatball',
      donor: 'Jason',
      location: 'Street2',
      contact: 9856213548,
      type:'Non-Veg',
      expiry:"24-03-2024",
      stars: 4.7,
      imageUrl: 'assets/food-2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id:'3',
      name: 'Hamburger',
      donor: 'John',
      location: 'Street3',
      contact: 9856213548,
      type:'Non-Veg',
      expiry:"24-03-2024",
      stars: 3.5,
      imageUrl: 'assets/food-3.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id:'4',
      name: 'Fried Potatoes',
      donor: 'Jynx',
      location: 'Street4',
      contact: 9856213548,
      type:'Veg',
      expiry:"24-03-2024",
      stars: 3.3,
      imageUrl: 'assets/food-4.jpg',
      tags: ['FastFood', 'Fry'],
    },
    {
      id:'5',
      name: 'Chicken Soup',
      donor: 'Jacob',
      location: 'Street5',
      contact: 9856213548,
      type:'Non-Veg',
      expiry:"24-03-2024",
      stars: 3.0,
      imageUrl: 'assets/food-5.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id:'6',
      name: 'Vegetables Pizza',
      donor: 'Jolene',
      location: 'Street6',
      contact: 9856213548,
      type:'Veg',
      expiry:"24-03-2024",
      stars: 4.0,
      imageUrl: 'assets/food-6.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
  ]

  export const sample_tags:Tag[] = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ]
